version: '3'

volumes:
  la_pg_data:
    driver: local
  la_mongo_data:
    driver: local

services:
#  db:
#    image: postgres:9.6
#    ports:
#      - 5432:5432
#    volumes:
#      - la_pg_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgrespass
#      POSTGRES_DB: link-aggregator
  mongo:
    image: mongo:4.0.3
    ports:
      - 27017:27017
    volumes:
      - la_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: link-aggregator
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8082:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root