version: '3'

volumes:
  la_pg_data:
    driver: local

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - la_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: link-aggregator